# Generated by Django 3.0 on 2020-11-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_privatechat_last_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechat',
            name='last_message_id',
        ),
        migrations.AddField(
            model_name='privatechat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message', to='chat.Message'),
        ),
    ]
