# Generated by Django 3.0 on 2020-11-22 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201122_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechat',
            name='last_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message', to='chat.Message'),
        ),
    ]
