# Generated by Django 3.0 on 2020-11-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201122_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechat',
            name='last_message',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
