# Generated by Django 3.0 on 2020-12-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201122_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chat.Message'),
        ),
    ]
