# Generated by Django 3.0 on 2020-03-06 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0002_course"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="course",),
        migrations.AddField(
            model_name="course",
            name="course",
            field=models.ManyToManyField(
                related_name="course", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
