# Generated by Django 3.0 on 2020-03-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_post_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="slug",),
    ]
