# Generated by Django 3.0 on 2020-04-02 17:43

from django.db import migrations, models
import django_uuid_upload
import functools


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_auto_20200402_1739"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.FileField(
                upload_to=functools.partial(
                    django_uuid_upload._upload_to_uuid_impl,
                    *(),
                    **{"make_dir": True, "path": "media/post_images", "remove_qs": True}
                ),
                verbose_name="Image",
            ),
        ),
    ]
