# Generated by Django 3.0 on 2020-04-04 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200402_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='guid_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
