# Generated by Django 3.0 on 2020-04-04 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200404_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='guid_url',
        ),
    ]
