# Generated by Django 3.0 on 2020-04-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_comment_reply"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="users",),
    ]
