# Generated by Django 3.0 on 2020-05-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_auto_20200503_0019"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
    ]
