# Generated by Django 3.0 on 2020-05-09 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_course_course_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_shared',
        ),
    ]
