# Generated by Django 3.0 on 2020-05-16 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0037_buzz_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buzz",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(550)]
            ),
        ),
    ]
