# Generated by Django 3.0 on 2020-06-15 22:36

from django.db import migrations
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("home", "0045_auto_20200612_2149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="Tags",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="buzz",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="Tags",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="Tags",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
