# Generated by Django 3.0 on 2020-06-28 01:40

from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0048_auto_20200623_1814"),
    ]

    operations = [BtreeGinExtension()]
