# Generated by Django 3.0 on 2020-06-28 02:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0050_auto_20200628_0148"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blog",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["sv"], name="search_idx_blog"
            ),
        ),
        migrations.AddIndex(
            model_name="buzz",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["sv"], name="search_idx_buzz"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["sv"], name="search_idx_course"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["sv"], name="search_idx_post"
            ),
        ),
    ]
