# Generated by Django 3.0 on 2020-08-12 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0055_courselist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseListObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_university', models.CharField(max_length=100)),
                ('course_instructor', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_courses', to='home.CourseList')),
            ],
        ),
    ]
