# Generated by Django 3.0 on 2020-11-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0066_professors_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="professors",
            name="name_slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="professors",
            name="university_slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
