# Generated by Django 3.0 on 2020-12-28 02:26

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0067_auto_20201117_2319"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="course_semester",),
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="CourseObject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=255)),
                ("sv", django.contrib.postgres.search.SearchVectorField(null=True)),
                (
                    "enrolled",
                    models.ManyToManyField(
                        blank=True,
                        related_name="enrolled_students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obj_dislikes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="course_obj_dislikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obj_likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="course_obj_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="courseobject",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["sv"], name="search_idx_course_obj"
            ),
        ),
    ]
