# Generated by Django 3.0 on 2020-12-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0068_auto_20201228_0226"),
    ]

    operations = [
        migrations.RemoveField(model_name="courseobject", name="obj_dislikes",),
        migrations.RemoveField(model_name="courseobject", name="obj_likes",),
    ]
