# Generated by Django 3.0 on 2020-12-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0069_auto_20201229_2030"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseobject",
            name="university_slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
