# Generated by Django 3.0 on 2020-12-30 01:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0070_courseobject_university_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="year",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1984),
                    django.core.validators.MaxValueValidator(2021),
                ],
                verbose_name="year",
            ),
        ),
    ]
