# Generated by Django 3.0 on 2020-12-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0071_review_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professors",
            name="courses",
            field=models.ManyToManyField(
                related_name="instructor_courses", to="home.CourseObject"
            ),
        ),
    ]
