# Generated by Django 3.1.5 on 2021-01-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_auto_20210103_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
    ]
