# Generated by Django 3.1.5 on 2021-01-07 23:37

from django.db import migrations, models
import django.utils.timezone
import django_uuid_upload
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_remove_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to=functools.partial(django_uuid_upload._upload_to_uuid_impl, *(), **{'make_dir': False, 'path': 'media/post_images/', 'remove_qs': True}), verbose_name='Image'),
            preserve_default=False,
        ),
    ]
