# Generated by Django 3.1.5 on 2021-01-31 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_review_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_prof_difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_reviews',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_interest',
        ),
    ]
