# Generated by Django 3.0 on 2020-03-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20200308_1902"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="slug",),
    ]
