# Generated by Django 3.0 on 2020-05-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_course_course_instructor_slug"),
        ("main", "0008_auto_20200502_2236"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="saved_courses",
            field=models.ManyToManyField(
                related_name="saved_courses", to="home.Course"
            ),
        ),
    ]
