# Generated by Django 3.0 on 2020-06-28 01:36

from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200627_2017'),
    ]

    operations = [
        BtreeGinExtension()
    ]
