# Generated by Django 3.0 on 2020-06-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_auto_20200628_0304"),
    ]

    operations = [
        migrations.AlterModelManagers(name="profile", managers=[],),
    ]
