# Generated by Django 3.0 on 2020-07-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_profile_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
