# Generated by Django 3.0 on 2020-07-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200706_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='public',
        ),
    ]
