# Generated by Django 3.0 on 2020-07-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_remove_profile_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="public",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
