# Generated by Django 3.0 on 2020-08-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_profile_rank_objects"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="save_searches",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
