# Generated by Django 3.0 on 2020-08-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_auto_20200824_0043"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="get_friendrequestaccepted_notify",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
