# Generated by Django 3.0 on 2020-10-08 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0035_notification"),
    ]

    operations = [
        migrations.DeleteModel(name="Notification",),
    ]
