# Generated by Django 3.0 on 2020-10-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20201018_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='get_post_notify_mentions',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
