# Generated by Django 3.0 on 2021-01-07 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_profile_get_post_notify_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
