# Generated by Django 3.0 on 2021-01-07 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
