# Generated by Django 3.1.5 on 2021-01-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20210107_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
