# Generated by Django 3.0 on 2020-06-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bookmarkblog_bookmarkbuzz_bookmarkpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
