# Generated by Django 3.0 on 2020-08-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_profile_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank_objects',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
