# Generated by Django 3.0 on 2020-04-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_post_guid_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='guid_url',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
