# Generated by Django 3.0 on 2020-05-07 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_course_is_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(350)]),
        ),
    ]
