# Generated by Django 3.0 on 2020-05-19 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0039_buzzreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buzzreply',
            name='reply_dislikes',
            field=models.ManyToManyField(blank=True, related_name='rdislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
