UNIVERSITY_CHOICES = (
    (
        "University",
        (
            ("", "University"),
            ("Acadia University", "Acadia University"),
            ("Alberta University of the Arts", "Alberta University of the Arts"),
            ("Algoma University", "Algoma University"),
            ("Athabasca University", "Athabasca University"),
            ("Atlantic School of Theology", "Atlantic School of Theology"),
            ("Bishop's University", "Bishop's University"),
            ("Booth University College", "Booth University College"),
            ("Brandon University", "Brandon University"),
            ("Brock University", "Brock University"),
            ("Canadian Mennonite University", "Canadian Mennonite University"),
            ("Cape Breton University", "Cape Breton University"),
            ("Capilano University", "Capilano University"),
            ("Carleton University", "Carleton University"),
            ("Concordia University", "Concordia University"),
            ("Crandall University", "Crandall University"),
            ("Dalhousie University", "Dalhousie University"),
            (
                "Emily Carr University of Art and Design",
                "Emily Carr University of Art and Design",
            ),
            ("Fairleigh Dickinson University", "Fairleigh Dickinson University"),
            (
                "Institut national de la recherche scientifique",
                "Institut national de la recherche scientifique",
            ),
            ("Kingswood University", "Kingswood University"),
            ("Kwantlen Polytechnic University", "Kwantlen Polytechnic University"),
            ("Lakehead University", "Lakehead University"),
            ("Laurentian University", "Laurentian University"),
            ("MacEwan University", "MacEwan University"),
            ("McGill University", "McGill University"),
            ("McMaster University", "McMaster University"),
            (
                "Memorial University of Newfoundland",
                "Memorial University of Newfoundland",
            ),
            ("Mount Allison University", "Mount Allison University"),
            ("Mount Royal University", "Mount Royal University"),
            ("Mount Saint Vincent University", "Mount Saint Vincent University"),
            ("New York Institute of Technology", "New York Institute of Technology"),
            ("Niagara University", "Niagara University"),
            ("Nipissing University", "Nipissing University"),
            (
                "Nova Scotia College of Art and Design University",
                "Nova Scotia College of Art and Design University",
            ),
            (
                "Ontario College of Art and Design University",
                "Ontario College of Art and Design University",
            ),
            ("Ontario Tech University", "Ontario Tech University"),
            ("Queen's University at Kingston", "Queen's University at Kingston"),
            ("Quest University", "Quest University"),
            ("Redeemer University College", "Redeemer University College"),
            ("Royal Military College of Canada", "Royal Military College of Canada"),
            ("Royal Roads University", "Royal Roads University"),
            ("Ryerson University", "Ryerson University"),
            ("Saint Francis Xavier University", "Saint Francis Xavier University"),
            ("Saint Mary's University", "Saint Mary's University"),
            ("Simon Fraser University", "Simon Fraser University"),
            ("St. Stephen's University", "St. Stephen's University"),
            ("St. Thomas University", "St. Thomas University"),
            ("The King's University", "The King's University"),
            ("Thompson Rivers University", "Thompson Rivers University"),
            ("Trent University", "Trent University"),
            ("Trinity Western University", "Trinity Western University"),
            ("Tyndale University", "Tyndale University"),
            ("University Canada West", "University Canada West"),
            ("University College of the North", "University College of the North"),
            ("University of Alberta", "University of Alberta"),
            ("University of British Columbia", "University of British Columbia"),
            ("University of Calgary", "University of Calgary"),
            ("University of Fredericton", "University of Fredericton"),
            ("University of Guelph", "University of Guelph"),
            ("University of King's College", "University of King's College"),
            ("University of Lethbridge", "University of Lethbridge"),
            ("University of Manitoba", "University of Manitoba"),
            ("University of New Brunswick", "University of New Brunswick"),
            (
                "University of Northern British Columbia",
                "University of Northern British Columbia",
            ),
            ("University of Ottawa", "University of Ottawa"),
            (
                "University of Prince Edward Island",
                "University of Prince Edward Island",
            ),
            ("University of Regina", "University of Regina"),
            ("University of Saskatchewan", "University of Saskatchewan"),
            ("University of Toronto", "University of Toronto"),
            ("University of Victoria", "University of Victoria"),
            ("University of Waterloo", "University of Waterloo"),
            ("University of Western Ontario", "University of Western Ontario"),
            ("University of Windsor", "Universityof Windsor"),
            ("University of Winnipeg", "University of Winnipeg"),
            ("University of the Fraser Valley", "University of the Fraser Valley"),
            ("Université Laval", "Université Laval"),
            ("Université Sainte-Anne", "Université Sainte-Anne"),
            ("Université de Moncton", "Université de Moncton"),
            ("Université de Montréal", "Université de Montréal"),
            ("Université de Sherbrooke", "Université de Sherbrooke"),
            ("Université de l'Ontario français", "Université de l'Ontario français"),
            (
                "Université du Québec en Abitibi-Témiscamingue",
                "Université du Québec en Abitibi-Témiscamingue",
            ),
            ("Université du Québec en Outaouais", "Université du Québec en Outaouais"),
            ("Université du Québec à Chicoutimi", "Université du Québec à Chicoutimi"),
            ("Université du Québec à Montréal", "Université du Québec à Montréal"),
            ("Université du Québec à Rimouski", "Université du Québec à Rimouski"),
            (
                "Université du Québec à Trois-Rivières",
                "Université du Québec à Trois-Rivières",
            ),
            ("Vancouver Island University", "Vancouver Island University"),
            ("Wilfrid Laurier University", "Wilfrid Laurier University"),
            ("York University", "York University"),
            ("Yukon University", "Yukon University"),
            ("École de technologie supérieure", "École de technologie supérieure"),
            (
                "École nationale d'administration publique",
                "École nationale d'administration publique",
            ),
        ),
    ),
)

# Add incoming student option only on signup
UNIVERSITY_CHOICES_SIGNUP = (
    ("Incoming Student", (("Incoming Student", "Incoming Student"),)),
    (
        "University",
        (
            ("", "University"),
            ("Acadia University", "Acadia University"),
            ("Alberta University of the Arts", "Alberta University of the Arts"),
            ("Algoma University", "Algoma University"),
            ("Athabasca University", "Athabasca University"),
            ("Atlantic School of Theology", "Atlantic School of Theology"),
            ("Bishop's University", "Bishop's University"),
            ("Booth University College", "Booth University College"),
            ("Brandon University", "Brandon University"),
            ("Brock University", "Brock University"),
            ("Canadian Mennonite University", "Canadian Mennonite University"),
            ("Cape Breton University", "Cape Breton University"),
            ("Capilano University", "Capilano University"),
            ("Carleton University", "Carleton University"),
            ("Concordia University", "Concordia University"),
            ("Crandall University", "Crandall University"),
            ("Dalhousie University", "Dalhousie University"),
            (
                "Emily Carr University of Art and Design",
                "Emily Carr University of Art and Design",
            ),
            ("Fairleigh Dickinson University", "Fairleigh Dickinson University"),
            (
                "Institut national de la recherche scientifique",
                "Institut national de la recherche scientifique",
            ),
            ("Kingswood University", "Kingswood University"),
            ("Kwantlen Polytechnic University", "Kwantlen Polytechnic University"),
            ("Lakehead University", "Lakehead University"),
            ("Laurentian University", "Laurentian University"),
            ("MacEwan University", "MacEwan University"),
            ("McGill University", "McGill University"),
            ("McMaster University", "McMaster University"),
            (
                "Memorial University of Newfoundland",
                "Memorial University of Newfoundland",
            ),
            ("Mount Allison University", "Mount Allison University"),
            ("Mount Royal University", "Mount Royal University"),
            ("Mount Saint Vincent University", "Mount Saint Vincent University"),
            ("New York Institute of Technology", "New York Institute of Technology"),
            ("Niagara University", "Niagara University"),
            ("Nipissing University", "Nipissing University"),
            (
                "Nova Scotia College of Art and Design University",
                "Nova Scotia College of Art and Design University",
            ),
            (
                "Ontario College of Art and Design University",
                "Ontario College of Art and Design University",
            ),
            ("Ontario Tech University", "Ontario Tech University"),
            ("Queen's University at Kingston", "Queen's University at Kingston"),
            ("Quest University", "Quest University"),
            ("Redeemer University College", "Redeemer University College"),
            ("Royal Military College of Canada", "Royal Military College of Canada"),
            ("Royal Roads University", "Royal Roads University"),
            ("Ryerson University", "Ryerson University"),
            ("Saint Francis Xavier University", "Saint Francis Xavier University"),
            ("Saint Mary's University", "Saint Mary's University"),
            ("Simon Fraser University", "Simon Fraser University"),
            ("St. Stephen's University", "St. Stephen's University"),
            ("St. Thomas University", "St. Thomas University"),
            ("The King's University", "The King's University"),
            ("Thompson Rivers University", "Thompson Rivers University"),
            ("Trent University", "Trent University"),
            ("Trinity Western University", "Trinity Western University"),
            ("Tyndale University", "Tyndale University"),
            ("University Canada West", "University Canada West"),
            ("University College of the North", "University College of the North"),
            ("University of Alberta", "University of Alberta"),
            ("University of British Columbia", "University of British Columbia"),
            ("University of Calgary", "University of Calgary"),
            ("University of Fredericton", "University of Fredericton"),
            ("University of Guelph", "University of Guelph"),
            ("University of King's College", "University of King's College"),
            ("University of Lethbridge", "University of Lethbridge"),
            ("University of Manitoba", "University of Manitoba"),
            ("University of New Brunswick", "University of New Brunswick"),
            (
                "University of Northern British Columbia",
                "University of Northern British Columbia",
            ),
            ("University of Ottawa", "University of Ottawa"),
            (
                "University of Prince Edward Island",
                "University of Prince Edward Island",
            ),
            ("University of Regina", "University of Regina"),
            ("University of Saskatchewan", "University of Saskatchewan"),
            ("University of Toronto", "University of Toronto"),
            ("University of Victoria", "University of Victoria"),
            ("University of Waterloo", "University of Waterloo"),
            ("University of Western Ontario", "University of Western Ontario"),
            ("University of Windsor", "Universityof Windsor"),
            ("University of Winnipeg", "University of Winnipeg"),
            ("University of the Fraser Valley", "University of the Fraser Valley"),
            ("Université Laval", "Université Laval"),
            ("Université Sainte-Anne", "Université Sainte-Anne"),
            ("Université de Moncton", "Université de Moncton"),
            ("Université de Montréal", "Université de Montréal"),
            ("Université de Sherbrooke", "Université de Sherbrooke"),
            ("Université de l'Ontario français", "Université de l'Ontario français"),
            (
                "Université du Québec en Abitibi-Témiscamingue",
                "Université du Québec en Abitibi-Témiscamingue",
            ),
            ("Université du Québec en Outaouais", "Université du Québec en Outaouais"),
            ("Université du Québec à Chicoutimi", "Université du Québec à Chicoutimi"),
            ("Université du Québec à Montréal", "Université du Québec à Montréal"),
            ("Université du Québec à Rimouski", "Université du Québec à Rimouski"),
            (
                "Université du Québec à Trois-Rivières",
                "Université du Québec à Trois-Rivières",
            ),
            ("Vancouver Island University", "Vancouver Island University"),
            ("Wilfrid Laurier University", "Wilfrid Laurier University"),
            ("York University", "York University"),
            ("Yukon University", "Yukon University"),
            ("École de technologie supérieure", "École de technologie supérieure"),
            (
                "École nationale d'administration publique",
                "École nationale d'administration publique",
            ),
        ),
    ),
)

UNI_LIST = [
    "Acadia University",
    "Alberta University of the Arts",
    "Algoma University",
    "Athabasca University",
    "Atlantic School of Theology",
    "Bishop's University",
    "Booth University College",
    "Brandon University",
    "Brock University",
    "Canadian Mennonite University",
    "Cape Breton University",
    "Capilano University",
    "Carleton University",
    "Concordia University",
    "Crandall University",
    "Dalhousie University",
    "Emily Carr University of Art and Design",
    "Fairleigh Dickinson University",
    "Institut national de la recherche scientifique",
    "Kingswood University",
    "Kwantlen Polytechnic University",
    "Lakehead University",
    "Laurentian University",
    "MacEwan University",
    "McGill University",
    "McMaster University",
    "Memorial University of Newfoundland",
    "Mount Allison University",
    "Mount Royal University",
    "Mount Saint Vincent University",
    "New York Institute of Technology",
    "Niagara University",
    "Nipissing University",
    "Nova Scotia College of Art and Design University",
    "Ontario College of Art and Design University",
    "Ontario Tech University",
    "Queen's University at Kingston",
    "Quest University",
    "Redeemer University College",
    "Royal Military College of Canada",
    "Royal Roads University",
    "Ryerson University",
    "Saint Francis Xavier University",
    "Saint Mary's University",
    "Simon Fraser University",
    "St. Stephen's University",
    "St. Thomas University",
    "The King's University",
    "Thompson Rivers University",
    "Trent University",
    "Trinity Western University",
    "Tyndale University",
    "University Canada West",
    "University College of the North",
    "University of Alberta",
    "University of British Columbia",
    "University of Calgary",
    "University of Fredericton",
    "University of Guelph",
    "University of King's College",
    "University of Lethbridge",
    "University of Manitoba",
    "University of New Brunswick",
    "University of Northern British Columbia",
    "University of Ottawa",
    "University of Prince Edward Island",
    "University of Regina",
    "University of Saskatchewan",
    "University of Toronto",
    "University of Victoria",
    "University of Waterloo",
    "University of Western Ontario",
    "University of Windsor",
    "University of Winnipeg",
    "University of the Fraser Valley",
    "Université Laval",
    "Université Sainte-Anne",
    "Université de Moncton",
    "Université de Montréal",
    "Université de Sherbrooke",
    "Université de l'Ontario français",
    "Université du Québec en Abitibi-Témiscamingue",
    "Université du Québec en Outaouais",
    "Université du Québec à Chicoutimi",
    "Université du Québec à Montréal",
    "Université du Québec à Rimouski",
    "Université du Québec à Trois-Rivières",
    "Vancouver Island University",
    "Wilfrid Laurier University",
    "York University",
    "Yukon University",
    "École de technologie supérieure",
    "École nationale d'administration publique",
]

UNIVERSITY_SLUGS = {
                        'Acadia University': 'acadia-university', 
                        'Alberta University of the Arts': 'alberta-university-of-the-arts', 
                        'Algoma University': 'algoma-university', 
                        'Athabasca University': 'athabasca-university',
                        'Atlantic School of Theology': 'atlantic-school-of-theology', 
                        "Bishop's University": 'bishops-university', 
                        'Booth University College': 'booth-university-college', 
                        'Brandon University': 'brandon-university', 
                        'Brock University': 'brock-university', 
                        'Canadian Mennonite University': 'canadian-mennonite-university', 
                        'Cape Breton University': 'cape-breton-university', 
                        'Capilano University': 'capilano-university', 
                        'Carleton University': 'carleton-university', 
                        'Concordia University': 'concordia-university', 
                        'Crandall University': 'crandall-university', 
                        'Dalhousie University': 'dalhousie-university', 
                        'Emily Carr University of Art and Design': 'emily-carr-university-of-art-and-design', 
                        'Fairleigh Dickinson University': 'fairleigh-dickinson-university', 
                        'Institut national de la recherche scientifique': 'institut-national-de-la-recherche-scientifique', 
                        'Kingswood University': 'kingswood-university', 
                        'Kwantlen Polytechnic University': 'kwantlen-polytechnic-university', 
                        'Lakehead University': 'lakehead-university', 
                        'Laurentian University': 'laurentian-university', 
                        'MacEwan University': 'macewan-university', 
                        'McGill University': 'mcgill-university', 
                        'McMaster University': 'mcmaster-university', 
                        'Memorial University of Newfoundland': 'memorial-university-of-newfoundland',
                        'Mount Allison University': 'mount-allison-university', 
                        'Mount Royal University': 'mount-royal-university', 
                        'Mount Saint Vincent University': 'mount-saint-vincent-university', 
                        'New York Institute of Technology': 'new-york-institute-of-technology', 
                        'Niagara University': 'niagara-university', 
                        'Nipissing University': 'nipissing-university',
                        'Nova Scotia College of Art and Design University': 'nova-scotia-college-of-art-and-design-university', 
                        'Ontario College of Art and Design University': 'ontario-college-of-art-and-design-university',
                        'Ontario Tech University': 'ontario-tech-university', 
                        "Queen's University at Kingston": 'queens-university-at-kingston', 
                        'Quest University': 'quest-university', 
                        'Redeemer University College': 'redeemer-university-college', 
                        'Royal Military College of Canada': 'royal-military-college-of-canada', 
                        'Royal Roads University': 'royal-roads-university', 
                        'Ryerson University': 'ryerson-university', 
                        'Saint Francis Xavier University': 'saint-francis-xavier-university', 
                        "Saint Mary's University": 'saint-marys-university', 
                        'Simon Fraser University': 'simon-fraser-university', 
                        "St. Stephen's University": 'st-stephens-university', 
                        'St. Thomas University': 'st-thomas-university', 
                        "The King's University": 'the-kings-university', 
                        'Thompson Rivers University': 'thompson-rivers-university', 
                        'Trent University': 'trent-university', 
                        'Trinity Western University': 'trinity-western-university', 
                        'Tyndale University': 'tyndale-university', 
                        'University Canada West': 'university-canada-west', 
                        'University College of the North': 'university-college-of-the-north', 
                        'University of Alberta': 'university-of-alberta', 
                        'University of British Columbia': 'university-of-british-columbia', 
                        'University of Calgary': 'university-of-calgary', 
                        'University of Fredericton': 'university-of-fredericton', 
                        'University of Guelph': 'university-of-guelph', 
                        "University of King's College": 'university-of-kings-college', 
                        'University of Lethbridge': 'university-of-lethbridge', 
                        'University of Manitoba': 'university-of-manitoba', 
                        'University of New Brunswick': 'university-of-new-brunswick', 
                        'University of Northern British Columbia': 'university-of-northern-british-columbia', 
                        'University of Ottawa': 'university-of-ottawa', 
                        'University of Prince Edward Island': 'university-of-prince-edward-island', 
                        'University of Regina': 'university-of-regina', 
                        'University of Saskatchewan': 'university-of-saskatchewan', 
                        'University of Toronto': 'university-of-toronto', 
                        'University of Victoria': 'university-of-victoria', 
                        'University of Waterloo': 'university-of-waterloo', 
                        'University of Western Ontario': 'university-of-western-ontario', 
                        'University of Windsor': 'university-of-windsor', 
                        'University of Winnipeg': 'university-of-winnipeg', 
                        'University of the Fraser Valley': 'university-of-the-fraser-valley', 
                        'Université Laval': 'universite-laval', 
                        'Université Sainte-Anne': 'universite-sainte-anne', 
                        'Université de Moncton': 'universite-de-moncton', 
                        'Université de Montréal': 'universite-de-montreal', 
                        'Université de Sherbrooke': 'universite-de-sherbrooke', 
                        "Université de l'Ontario français": 'universite-de-lontario-francais', 
                        'Université du Québec en Abitibi-Témiscamingue': 'universite-du-quebec-en-abitibi-temiscamingue', 
                        'Université du Québec en Outaouais': 'universite-du-quebec-en-outaouais', 
                        'Université du Québec à Chicoutimi': 'universite-du-quebec-a-chicoutimi', 
                        'Université du Québec à Montréal': 'universite-du-quebec-a-montreal', 
                        'Université du Québec à Rimouski': 'universite-du-quebec-a-rimouski', 
                        'Université du Québec à Trois-Rivières': 'universite-du-quebec-a-trois-rivieres', 
                        'Vancouver Island University': 'vancouver-island-university', 
                        'Wilfrid Laurier University': 'wilfrid-laurier-university', 
                        'York University': 'york-university', 
                        'Yukon University': 'yukon-university', 
                        'École de technologie supérieure': 'ecole-de-technologie-superieure', 
                        "École nationale d'administration publique": 'ecole-nationale-dadministration-publique'
                    }